### ISSUE TITLE
Support for commenting on community posts

### ISSUE THREAD

**Issue by Kotakas** [3urobeat/steam-comment-service-bot#128]
A Bot which will not comment on peoples profile but it will comment they're posts on the community discussions

**Comment by HerrEurobeat** [comment]
Hey, thanks for opening an issue and sorry for the very late response.  
This idea came up already round about a year ago however I never pursued the idea because the library I'm using to interact with the SteamCommunity doesn't provide a function for this.  
This means that I would probably have to do HTTP request stuff myself and figure out how to post these kind of comments manually.  
  
For now this is too much work for me although I might revisit the idea sometime in the future.

**Comment by 3urobeat** [comment]
I have now added support for commenting on group, app and forum discussions.  
I'll keep this issue open until the feature is released in Version 2.14.0 in the master branch.

**Comment by 3urobeat** [comment]
Version 2.14 is out on master which adds support for this suggestion.  
Check out the release notes [here](https://github.com/3urobeat/steam-comment-service-bot/releases/tag/2.14.0)!
