### ISSUE TITLE
Primary Group setting throws HTTP 429 error

### ISSUE THREAD

**Issue by Beyulium** [3urobeat/steam-comment-service-bot#165]
**Error/Element that doesn't work**
Please include the full error you get or if you get none, describe precisely what happened.

**Additional information**
Please add any other information here if you have some.

**Comment by HerrEurobeat** [comment]
Hey, thanks for opening an issue.  
First of all, thank you for the donation! I really appreciate it :)  

As far as I'm concerned updating/setting the primary group isn't supported by `node-steamcommunity` at the moment. I did open a PR back when I added support for setting a primary group here as Steam does allow it but there was no response yet: https://github.com/DoctorMcKay/node-steamcommunity/pull/287  

The HTTP 429 error itself is a sign that the bot is attempting to do the same request from the same IP too often in a short timeframe. I'm not sure why this is happening as this request is made only after logging in and only once per account.  
Since the feature is not supported anyway at the moment I'd recommend you to just turn it off in your `advancedconfig.json` for now by setting `setPrimaryGroup` to `false` (which is the default setting).  

I'll take a look at if it would make sense to add more delays to the call in the future. I'm not sure how severely Steam limits editProfile() calls.

**Comment by 3urobeat** [comment]
Sorry for not updating this issue earlier - updating the primary group is supported now.  
I myself have not seen the HTTP 429 error which was the reason why this issue was created, so I'm going to close this issue for now.  
If this error reoccurs then please reopen this issue!
