### ISSUE TITLE
HTTP 429 error 

### ISSUE THREAD

**Issue by anedely** [3urobeat/steam-comment-service-bot#187]
**Describe the bug**
What happened?

**Full error**
Please post the **complete** error here!

**Additional context**
Please add any other information here if you have some.

https://prnt.sc/6GdZlHr0uveA

**Comment by 3urobeat** [comment]
Hey, thanks for opening an issue.  

As [described in the wiki](https://github.com/3urobeat/steam-comment-service-bot/blob/master/docs/wiki/errors_doc.md#steam-errors), `HTTP 429` is a rate limit error returned by Steam.  
It means that the IP that account uses has made too many requests in a short period of time and needs to wait a bit before trying again. This is **intended behavior** from Steam and not a bug.  
Since you are not using proxies based on the screenshot, and therefore all accounts are using the same IP, the bot aborted the request because all further comments will fail too.

The only thing you can do is either request less, increase the `commentdelay` set in the config or use proxies (which is the most effective).  

I hope this clears things up for you :)
