### ISSUE TITLE
Comment announcements question

### ISSUE THREAD

**Issue by tailon222** [3urobeat/steam-comment-service-bot#219]
Hello! i have been looking at the `!comment` command, and i saw that you implemented a feature to comment announcements but is only for the  **General Discussions** threads, aka "discussions".  Will it be possible to make it also comment  **Events & Announcements** threads? aka "eventcomments"  i think it works the same way, but they hide the user that posted it (which you can get it by  inspecting the report button or the block button anyway) that way you can get the steamID64 to post the comment. Honestly i tried to modify it but i don't know what i am doing plus I'm getting the file restored every time because it detects changes on files.  I also tried to post the link and it gave me an error.

**Example Threads link:** 
`https://steamcommunity.com/app/578080/eventcomments/`

**Also the button thing i was talking about:**
Usually the class is called: `forum_comment_action report tooltip`  and i'm pretty sure is same in every game.

**Comment by 3urobeat** [comment]
Hey, thanks for opening an issue.  

If you want to make changes to the bot for contributing you must run the `generateFileStructure.js` script before starting the bot.  
This script refreshes the checksum for every file so that the dataIntegrity check does not detect the file as broken.  
This is documented at the bottom of the [Contributing Wiki page](https://github.com/3urobeat/steam-comment-service-bot/blob/beta-testing/docs/wiki/contributing.md#starting-the-bot). You can also start the bot using the command `npm run dev` which will do this automatically for you.   
Also make sure you are on the beta-testing branch (but that is all explained on the Contributing Wiki page).

The comment command itself just figures out the type of ID provided by the user, does cooldown checks etc and then calls the correct function of the steamcommunity library. Discussions support is currently implemented as a [library patch here](https://github.com/3urobeat/steam-comment-service-bot/blob/beta-testing/src/libraryPatches/discussions.js) because my PR is not yet merged upstream.  
I actually didn't know that there is another type of discussion - I have to see how and if the endpoint for posting there differs from "normal" discussions.

**Comment by tailon222** [comment]
Okay, thanks for the info i'll try to do it myself although i don't think i  would be able to, i don't really know what i am doing, just learning how your modified library works with the "normal" forum comments. 

The forum structure is the same, so i don't think it will be much different, the only thing probably is the way to get the steamID64.

As an idea, would be awesome to add to the `!comment` command a way to detect if is a link from a "normal" forum or from the other one. As you can see, there is an ID in both links, one of the different things is that the normal forum is called _"discussions"_ and the event forum is called _"eventcomments"_

**Example links for the normal forum:**
https://steamcommunity.com/app/578080/discussions/1/6699729218449153233/ 
**Example links for the event forum:**
https://steamcommunity.com/app/578080/eventcomments/3968295633410961258/


If you think of implementing it let me know, if not then is good too.


**Thank you so much for your time and amazing work!**

**Comment by 3urobeat** [comment]
No worries, any contribution is welcome :)  
No pressure though - this projects has gotten quite large over time, I totally understand if it's overwhelming.

The library patches system allows us to overwrite existing methods in the library and to add new ones.  
The methods in the discussions.js file which I linked replicate the corresponding request which you'd do with your browser when clicking the post comment button for example.  
To reverse-engineer one you can use the Network tab in the developer tools of your browser. It will record all the requests sent when for example clicking a button on that page.

I forgot to mention in my comment above how the bot detects the type of a link/ID.
The comment command calls `getCommentArgs()` which processes the parameters the user provided (amount, id, custom quotes). This helper function then again calls `handleSteamIdResolving()` which attempts to figure out which type of link or ID the user provided and converts it to a steamID64.  
[1](https://github.com/3urobeat/steam-comment-service-bot/blob/beta-testing/src/commands/core/comment.js#L89) -> [2](https://github.com/3urobeat/steam-comment-service-bot/blob/beta-testing/src/commands/helpers/getCommentArgs.js#L88) -> [3](https://github.com/3urobeat/steam-comment-service-bot/blob/beta-testing/src/controller/helpers/handleSteamIdResolving.js)  

In this case of a discussion `handleSteamIdResolving()` doesn't need to convert the link to an ID, it just detects it.   
Recognizing eventcomments shouldn't be hard, it's just copy&pasting the discussion `else if` block from line [70](https://github.com/3urobeat/steam-comment-service-bot/blob/b4072cfdc35d311d595150fe692e60ac6135aa43/src/controller/helpers/handleSteamIdResolving.js#L70) and changing dicussions to eventcomments (I think).  
Then the comment command would need to know which method of the library to use for that type, which is done in line [164](https://github.com/3urobeat/steam-comment-service-bot/blob/b48243eeae4e7d109e4ef12f8da08fc03950ee4b/src/commands/core/comment.js#L164) and below.  

I hope I was able to at least explain how the bot processes a request and I hope I didn't forget anything.  
Feel free to experiment if you want, otherwise I'll take a look at it when I'll start working on the next update ^^

**Comment by tailon222** [comment]
Thank you for all the info!
now i know how to edit the code and experiment with it.

I tried what you said with the`else if` block, and i'm getting this error: `[2023-11-20 19:57:45 | ERROR] Couldn't get discussion even though it exists?! Aborting!
TypeError: Cannot read properties of undefined (reading 'includes')`

Do i have to also modify the idType = "discussion";  to idType = "eventcomments"; ?
Do i have to edit the comment.js file in the line 164? 

I feel like is not enough with that and that i should edit [this](https://github.com/3urobeat/steam-comment-service-bot/blob/b48243eeae4e7d109e4ef12f8da08fc03950ee4b/src/libraryPatches/CSteamDiscussion.js#L61) and create another line with "eventcomments".
And also [this](https://github.com/3urobeat/steam-comment-service-bot/blob/b48243eeae4e7d109e4ef12f8da08fc03950ee4b/src/libraryPatches/CSteamDiscussion.js#L165) and call it getEventComments and also use "eventcomments" instead of discussions

I'll try some other ideas, if i can't get it to work i will just wait to next update. Not a big deal :)

**Comment by 3urobeat** [comment]
Yes, if the request you are adding uses a different function in the library then you need to change the idType as well.  
Since the request you are adding seems to be incompatible with the "normal" discussions, you are getting the error you posted (which is handled in the comment command in line 201).  

If you add a new idType then you also need to handle that type of id in the comment command, yes.  

I'm assuming there are enough differences between these two types of discussions that the current library function is unable to handle them both.  
There is probably more that needs to be done in the library patch but I can't say for sure without checking it out myself.

**Comment by 3urobeat** [comment]
Support for commenting on eventcomments discussions has been added and will be shipped in v2.15.0.  

Please note that limited accounts might not be able to comment on a game's eventcomments post.  
While testing I have noticed that my limited accounts were able to comment on CS2, TF2 and some other game's posts; however not on posts from PUBG or Helldivers 2.  
I didn't implement any checks for that as of now, the comments will just fail with `Error: The settings on this account do not allow you to add comments.`.

I'll keep this issue open until v2.15.0 is out on the master branch.

**Comment by 3urobeat** [comment]
Nvm, I added support for filtering out accounts that are unable to comment on that discussion.

**Comment by 3urobeat** [comment]
Version 2.15 is now out on the master branch and adds support for this suggestion.
Check out the release notes [here](https://github.com/3urobeat/steam-comment-service-bot/releases/tag/2.15.0)!
