### ISSUE TITLE
s

### ISSUE THREAD

**Issue by jahreininsolu** [3urobeat/steam-comment-service-bot#220]
**Describe the solution you'd like**
A clear description of what should happen.

**Additional context**

Adding games to the library. I want to add some games to my bot accounts' library using a shortcut.

+ 
artwork like favorite 

+ 
games review like

**Comment by Sam1230000** [comment]
Yes

**Comment by 3urobeat** [comment]
Hey, how is this game library adding feature supposed to look like? The bot already automatically redeems licenses for free games when set in the config.  
Favorizing and voting on artworks is already supported since Version 2.13.0, see the corresponding [changelog](https://github.com/3urobeat/steam-comment-service-bot/blob/master/docs/wiki/changelogs/CHANGELOG_v2.13.md#2023-06-05-version-2130-co-author-derdeathraven) "Added support for [...] voting & favorizing sharedfiles".  
Voting and commenting on reviews is already planned for v2.15, see #207

**Comment by jahreininsolu** [comment]
thanks
