### ISSUE TITLE
jag behöver hjälp

### ISSUE THREAD

**Issue by kru2006** [3urobeat/steam-comment-service-bot#221]
**Describe the bug**
What happened?

**Full error**
Please post the **complete** error here!

**Additional context**
Please add any other information here if you have some.

3 vänner till oss använder detta. Jag förstod inte mycket. kan du hjälpa mig?

**Comment by 3urobeat** [comment]
Sorry, I do not speak Swedish.  

**Original issue, translated:**
> jag behöver hjälp

I need help

> 3 vänner till oss använder detta. Jag förstod inte mycket. kan du hjälpa mig?

3 friends of ours use this. I didn't understand much. can you help me?

&nbsp;

What exactly do you not understand? Please explain so that I can attempt to help you.  

What the bot does and how you can set it up is explained in the [README.md](https://github.com/3urobeat/steam-comment-service-bot/blob/master/README.md), as well as in the corresponding [YouTube tutorial](https://youtu.be/8J78rC9Z28U).  

This application is a Steam Bot Account Manager, with built-in commenting, favorizing, liking, etc. support.  
It logs into a bunch of accounts which you provide and uses them to fulfill comment etc. requests, made through the Steam Chat.  
It can also be used as a base for other projects by creating plugins, to make use of its capabilities.
