### ISSUE TITLE
Steam rateup - follow - review 

### ISSUE THREAD

**Issue by ayanamidiscord** [3urobeat/steam-comment-service-bot#223]
**Describe the bug**
What happened?

**Full error**
Please post the **complete** error here!

**Additional context**
Please add any other information here if you have some.

**Comment by 3urobeat** [comment]
Hey, I guess you wanted to open a feature suggestion issue and not a bug report?  

Either way - rateup is already implemented since version 2.13, use the !upvote and !downvote commands.  
Following is already support since version 2.14, use the !follow & !unfollow commands.  
Game reviewing is already proposed in #207

**Comment by aynisinemeler** [comment]
review boost may be useful for me. this would be nice.

**Comment by veleysiz** [comment]
rateup failed e

**Comment by DoubleFurke** [comment]
@3urobeat

**Comment by 3urobeat** [comment]
Closing as duplicate in favor for #207  
Issue 207 will be receive updates until v2.15 is out, which will include support for commenting & voting on reviews.  
Thanks!
