### ISSUE TITLE
Hosting

### ISSUE THREAD

**Issue by Hamstermans** [3urobeat/steam-comment-service-bot#238]
**Question or issue you are experiencing**
Hello, I would like to host this tool online 24/7. What would be needed to do this? Do I need a vps for this or does web hosting work as well? If a vps is required, do you recommend the usage of a linux or windows vps? Thanks a lot in advance!

**Comment by 3urobeat** [comment]
Hey, thanks for opening an issue!  
I don't have any experience with hosting services because I have my own server at home.  

In any case you need something that runs 24/7, I guess a cheap VPS would be fitting. A web hosting service wouldn't work.  
I'd always recommend Linux over Windows; but especially for servers.  

You really don't need much power to run this project, even a Raspberry Pi 3B would be enough. My instance usually uses around 130MB RAM (but plan with a bit more to be sure, let's just say 500MB) and it doesn't really tax the CPU at all.

**Comment by Hamstermans** [comment]
Thanks a lot for your help! It took me a while to set everything up as I am not familiar with linux, but everything is working as intended now!

**Comment by 3urobeat** [comment]
Awesome! Have fun!  
If you have more questions later on, feel free to open another issue :)
